### ISSUE TITLE
Defect: unable to see department name of employee

### ISSUE THREAD

**Issue by ieiunium** [MikalaiKazak/StuffManagment#24]
when I open http://localhost:8080/webapp/employees then I see list of employees without department name,
when I open http://localhost:8080/webapp/employee/0 then I could not see department name of particular employee either

**Comment by ieiunium** [comment]
expected: see not only raw department id, but department name

**Comment by MikalaiKazak** [comment]
I start work

**Comment by MikalaiKazak** [comment]
I fixed the defect
