### ISSUE TITLE
Defect: incorrect average salary

### ISSUE THREAD

**Issue by ieiunium** [MikalaiKazak/StuffManagment#26]
I have added two employees with salaries 1 and 2 in first department 
and I have added two employees with salaries 3 and 4 in second department 
then I open http://localhost:8080/webapp/departments and see 
![image](https://user-images.githubusercontent.com/8763075/51250911-ffe66480-19a8-11e9-82d8-356eec999341.png)

expected: 1.5 and 3.5

**Comment by MikalaiKazak** [comment]
I start work

**Comment by MikalaiKazak** [comment]
I fix salary
